package SeleneumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestPagesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "src/test/resources/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testPages() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(2560, 1377));
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.cssSelector(".title")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("u"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".contentBody > div")).click();
    driver.findElement(By.linkText("Actors")).click();
    {
      WebElement element = driver.findElement(By.linkText("Actors"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".title")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("u"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Films")).click();
    driver.findElement(By.cssSelector("u")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("u"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.cssSelector(".title")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("u"));
      assert(elements.size() > 0);
    }
  }
}
